= "I really wish that Microsoft would allow this 'feature' to be turned off"
:hp-tags: FTS, sqlserver2012, sqlserver2008r2

На днях зіштовхнулась з проблемою, FTS повертав на одному й тому ж наборі даних, але на різних машинах (MS SQL 2012 vs MS SQL 2008 R2), різні результати для значення «050056». В одному випадку це були всі рядки, в яких зустрічалось тільки 050056 (2008 R2), а в іншому – 0 на початку ігнорувався і вибирались всі значення з 50056.

Виявилось, що в такій поведінці «винні» word breakers, логіка яких змінилась в MS SQL 2012. Якщо подивитись, які терми створюються на різних версіях SQL Server (select * from  sys.dm_fts_parser('050056', 1033, null, 0)), то побачимо, що в MS SQL 2008 R2 це «050056» та «nn050056»,  а в оновленій версії - «050056» та «nn50056» (!)
Змінити таку поведінку можна, повернувшись, до попередньої версії Word Breakers - https://msdn.microsoft.com/en-us/library/gg509108.aspx

Або ж створивши свій власний словник – https://msdn.microsoft.com/en-us/library/hh231252.aspx

Ну, або додати додатковий LIKE поверх того, що поверне FTS і вибрати ті значення, що починаються з 0.

Ось тут решта змін, що вплинули на роботу повнотекстового пошуку - https://msdn.microsoft.com/en-us/library/ms143272.aspx